swagger: "2.0"
info:
  version: "0.0.1"
  title: Happy Home API
# basePath prefixes all resource paths
basePath: /api
# 
schemes:
  # tip: remove http to make production-grade
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
tags:
- name: "sample"
  description: "サンプルAPI"
- name: "notice_list/new"
  description: "最新通知リスト関連（高井）"
- name: "notice_list/old"
  description: "過去通知リスト関連（高井）"
- name: "suggestion"
  description: "提案関連（浅川）"
- name: "emotions"
  description: "感情関連（浅川）"
paths:
  /sample:
    x-swagger-router-controller: sample
    get:
      tags:
      - "sample"
      summary: サンプルget
      parameters:
        - name: id
          in: query
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Sample"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /notice_list/new:
    x-swagger-router-controller: new_notice_list
    get:
      tags:
      - "notice_list/new"
      summary: 最新の通知リストを取得
      operationId: getNewNoticeList
      parameters:
        - name: family_structure_id
          in: query
          description: 端末の利用者を識別する。
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Notice"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /notice_list/new/{id}:
    x-swagger-router-controller: new_notice_list
    get:
      tags:
      - "notice_list/new"
      summary: 最新の通知リストの詳細取得
      operationId: getNewNoticeDetail
      parameters:
      - name: "id"
        in: "path"
        description: "通知ID"
        required: true
        type: integer
        format: base64
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/NoticeDetail"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /notice_list/old:
    x-swagger-router-controller: old_notice_list
    get:
      tags:
      - "notice_list/old"
      summary: 過去の通知リストを取得
      operationId: getOldNoticeList
      parameters:
        - name: family_structure_id
          in: query
          description: 端末の利用者を識別する。
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Notice"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /notice_list/old/{id}:
    x-swagger-router-controller: old_notice_list
    get:
      tags:
      - "notice_list/old"
      summary: 最新の通知リストの詳細取得
      operationId: getOldNoticeDetail
      parameters:
      - name: "id"
        in: "path"
        description: "通知ID"
        required: true
        type: integer
        format: base64
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/NoticeDetail"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /suggestion/{id}:
    x-swagger-router-controller: suggestion
    get:
      tags:
      - "suggestion"
      summary: 提案詳細取得
      operationId: getSuggesrionDetail
      parameters:
      - name: "id"
        in: "path"
        description: 提案ID
        required: true
        type: integer
        format: base64
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuggestionDetail"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /emotions:
    x-swagger-router-controller: emotions
    post:
      tags:
      - "emotions"
      summary: 感情データ登録
      description: 家族IDはt_family.timestampから最新のIDをAPIが取得し紐付ける。
      operationId: postEmotions
      parameters:
      - name: "json_data"
        in: "formData"
        description: 感情情報JSON
        required: true
        type: string
      - name: "image_path"
        in: "formData"
        description: 読み取った感情画像パス
        required: true
        type: string
      responses:
        "204":
          description: Success
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  Sample:
    properties:
      id:
        type: integer
      name:
        type: string
      age:
        type: integer
  ErrorResponse:
    required:
      - message
      - status
      - ok
    properties:
      message:
        type: string
      status:
        type: integer
      ok:
        type: boolean
        default: false
  SuggestionTask:
    properties:
      id:
        type: integer
        description: タスクID
      contents:
        type: string
        description: タスク内容
      is_done:
        type: boolean
        description: タスク完了(true)、未完了(false)
  Notice:
    properties:
      id:
        type: string
      family_structure_id:
        type: integer
        description: 家族構成ID
      title:
        type: string
        description: 通知タイトル
      suggestion_id:
        type: integer
        description: 提案受け入れID、まだの場合はnull
  Suggestion:
    properties:
      id:
        type: integer
      title:
        type: string
  FamilyStructure:
    properties:
      id:
        type: integer
      family_id:
        type: integer
      name:
        type: string
      family_type:
        type: string
  SuggestionDetail:
    properties:
      id:
        type: integer
        description: 提案ID
      title:
        type: string
      point:
        type: integer
      family_structure:
        $ref: "#/definitions/FamilyStructure"
      task_list:
        type: array
        items:
          $ref: "#/definitions/SuggestionTask"
  NoticeDetail:
    properties:
      id:
        type: integer
      family_strcuture_id:
        type: integer
        description: 家族構成ID
      title:
        type: string
        description: 通知タイトル
      notice_contents:
        type: string
        description: 通知内容
      suggestion_list:
        type: array
        items:
          $ref: "#/definitions/Suggestion"